Handle case of double "-" chars in input component
tahowallet/dapp pull request #826
Opened 2023-12-04 10:25 UTC by xpaczka

Resolves #161

2023-12-05 20:02 UTC, ioay requested changes

2023-12-05 20:02 UTC, ioay commented on src/shared/components/TokenAmountInput.tsx
> +  if (parsed !== undefined && parsed > balance) {
Let's write it down more clearly, group by conditions not by results(more human-readable):

```
if(!parsed){
  if(value} ...
}
if(parsed){
  if(parsed < 0n) ...
  if(parsed > balance) ...
}
```

2023-12-05 20:06 UTC, ioay commented
When you want to unstake and you will enter the max value manually button is disabled, in the case when you click the max button in the input field - the button `unstake` becomes active.
<img width="334" alt="Screenshot 2023-12-05 at 20 45 23" src="https://github.com/tahowallet/dapp/assets/28560653/0839caa0-0304-439d-aced-0f1b45e1cf65">
<img width="332" alt="Screenshot 2023-12-05 at 20 45 41" src="https://github.com/tahowallet/dapp/assets/28560653/6ea81652-8a78-4a84-8c2c-73ddc5c7203c">

2023-12-06 06:49 UTC, xpaczka commented
> When you want to unstake and you will enter the max value manually button is disabled, in the case when you click the max button in the input field - the button `unstake` becomes active. <img alt="Screenshot 2023-12-05 at 20 45 23" width="334" src="https://private-user-images.githubusercontent.com/28560653/288189254-0839caa0-0304-439d-aced-0f1b45e1cf65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDU1MjYsIm5iZiI6MTcwMTg0NTIyNiwicGF0aCI6Ii8yODU2MDY1My8yODgxODkyNTQtMDgzOWNhYTAtMDMwNC00MzlkLWFjZWQtMGYxYjQ1ZTFjZjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA2NDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZTYwODE2ZjdkOGQ5ODc3Zjg5MTZhNjZlODBmMzExZjVkMGIxYWE2ZDQ4MGYzOGZkMjA0ZjJiYTRkMmI4MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Esu2Irx9PiUl1JnXmWSdsXeFZaGL74aijnOX5HuI1rA"> <img alt="Screenshot 2023-12-05 at 20 45 41" width="332" src="https://private-user-images.githubusercontent.com/28560653/288189255-6ea81652-8a78-4a84-8c2c-73ddc5c7203c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDU1MjYsIm5iZiI6MTcwMTg0NTIyNiwicGF0aCI6Ii8yODU2MDY1My8yODgxODkyNTUtNmVhODE2NTItOGE3OC00YTg0LThjMmMtNzNkZGM1YzcyMDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA2NDcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YzQxYjNhZTIyMzM3ZmMzZTMwY2I5ZWRkMTNhYTYzYjFhMjE4ZTVjNmM2ZDJkYTYwNjdmMGQyZjY4ZGM5OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j7UvyBzTjgV4weXAIhvuo68E4yDwuPiVEjXPi2-R9hk">

It is an issue that was there before, I wasn’t able to resolve it, it happens in some cases

2023-12-06 08:07 UTC, xpaczka commented on src/shared/components/TokenAmountInput.tsx
> +        acceptLetters={false}
The "number" input does not resolve the issue here, it still accepts double "-" char

2023-12-06 08:28 UTC, xpaczka commented on src/shared/components/TokenAmountInput.tsx
> +        acceptLetters={false}
https://stackoverflow.blog/2022/12/26/why-the-number-input-is-the-worst-input/

Cool article, why using "number" input is the worst :)

2023-12-06 09:31 UTC, ioay submitted a review, later dismissed
lgtm, just one minor comment

2023-12-06 09:31 UTC, ioay commented on src/shared/components/Input.tsx
> +    (inputValue: string) => {
```suggestion
    (e: Event) => {
```

2023-12-06 10:27 UTC, ioay approved these changes

2023-12-06 10:27 UTC, merged

2023-12-06 10:32 UTC, jagodarybacka commented on src/shared/components/Input.tsx
> +  const isTypeNumber = useMemo(() => type === "number", [type])
is useMemo doing anything? both "type" is a string and "isTypeNumber" is a boolean - they shouldn't cause rerenders or trigger changes without actually changing values, right?

2023-12-06 10:32 UTC, jagodarybacka commented on src/shared/components/Input.tsx
> +      if (inputValue === "") onChange?.("")
shouldn't we "return" in this line?

2023-12-06 17:13 UTC, Shadowfiend commented on src/shared/components/TokenAmountInput.tsx
> +        acceptLetters={false}
That `inputmode` trick is nice :eyes: